[package]
name = "donuts"
version = "0.1.0"
authors = ["Cedric Hutchings <cedhut02@gmail.com>"]
edition = "2018"

[features]
donutvision = []

[dependencies]
macroquad = { git = "https://github.com/cedric-h/macroquad.git", branch = "noskew2" }
